In [1]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import math

# Load pre-trained model and tokenizer
model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Encode the sentence
sentence = "I love you"
inputs = tokenizer(sentence, return_tensors="pt")

# Compute log probabilities
with torch.no_grad():
    outputs = model(**inputs, labels=inputs["input_ids"])
    log_likelihood = -outputs.loss.item() * inputs["input_ids"].size(1)
    sentence_probability = math.exp(log_likelihood)

print(f"Log Probability: {log_likelihood}")
print(f"Sentence Probability: {sentence_probability}")

`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.


Log Probability: -14.554902076721191
Sentence Probability: 4.774043187329362e-07


In [2]:
logits = outputs.logits

In [3]:
input_ids = inputs["input_ids"]

In [4]:
input_ids

tensor([[  40, 1842,  345]])

In [5]:
shift_logits = logits[:, :-1, :].contiguous()

In [6]:
shift_logits

tensor([[[-39.3081, -39.0097, -41.8371,  ..., -46.9333, -44.9070, -39.5146],
         [-84.4959, -85.0685, -90.6137,  ..., -91.6658, -93.1033, -87.5302]]])

In [7]:
shift_labels = input_ids[:, 1:].contiguous()

In [8]:
shift_labels

tensor([[1842,  345]])

In [9]:
import torch.nn.functional as F

log_probs = F.log_softmax(shift_logits, dim=-1)

In [10]:
log_probs

tensor([[[ -6.4495,  -6.1511,  -8.9785,  ..., -14.0748, -12.0484,  -6.6560],
         [ -8.3049,  -8.8775, -14.4227,  ..., -15.4748, -16.9124, -11.3392]]])

In [11]:
log_probs_for_tokens = log_probs.gather(2, shift_labels.unsqueeze(-1)).squeeze(-1)

In [12]:
log_probs_for_tokens

tensor([[-7.3372, -2.3661]])

In [13]:
total_log_prob = log_probs_for_tokens.sum().item()

In [14]:
total_log_prob

-9.703268051147461

In [15]:
sentence_probability = torch.exp(torch.tensor(total_log_prob)).item()

In [16]:
sentence_probability

6.108354136813432e-05

In [17]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import math
import torch.nn.functional as F

model_name = "meta-llama/Meta-Llama-3-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.float16)

def cal_part_logprob(input_text: str, _tokenizer):

    # Load pre-trained model and tokenizer
    # model_name = "gpt2"

    # model = AutoModelForCausalLM.from_pretrained(model_name)
    # model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.float16)

    
    # Encode the sentence
    sentence = input_text
    inputs = _tokenizer(sentence, return_tensors="pt")
    
    # Compute log probabilities
    with torch.no_grad():
        outputs = model(**inputs, labels=inputs["input_ids"], loss_type='ForCausalLMLoss')

    logits = outputs.logits
    input_ids = inputs["input_ids"]
    shift_logits = logits[:, :-1, :].contiguous()
    shift_labels = input_ids[:, 1:].contiguous()

    log_probs = F.log_softmax(shift_logits, dim=-1)
    log_probs_for_tokens = log_probs.gather(2, shift_labels.unsqueeze(-1)).squeeze(-1)
    total_log_prob = log_probs_for_tokens.sum().item()
    avg_logProb = total_log_prob/len(input_ids[0])

    return log_probs_for_tokens, total_log_prob, avg_logProb
    
    # sentence_probability = torch.exp(torch.tensor(total_log_prob)).item()

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [1]:
import torch

torch.cuda.empty_cache()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import math
import torch.nn.functional as F

model_name = "meta-llama/Meta-Llama-3-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.float16)
tokenizer.pad_token = tokenizer.eos_token
model.resize_token_embeddings(len(tokenizer))
model = model.to(device)

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [23]:
# inputs = tokenizer('I love you', return_tensors="pt").to(device)
# tokenizer.add_special_tokens({'pad_token': '[PAD]'})
# tokenizer.pad_token = tokenizer.eos_token
# model.resize_token_embeddings(len(tokenizer))
inputs = tokenizer(['I like drinking Earl Grey', 'I love you', 'But I hate you'], return_tensors="pt", padding=True, truncation=True, max_length=512).to(device)

In [24]:
print(inputs["input_ids"].device)
print(model.device)

cuda:0
cuda:0


In [25]:
attention_mask = inputs["attention_mask"]

outputs = model(**inputs, labels=inputs["input_ids"], loss_type='ForCausalLMLoss')

In [26]:
logits = outputs.logits

In [27]:
logits.shape

torch.Size([3, 6, 128256])

In [28]:
# shift_logits = logits_list[:-1, :].contiguous()
# shift_logits.shape

In [59]:
input_ids = inputs["input_ids"]


shift_logits = logits[: , :-1, :].contiguous()
shift_labels = input_ids[:, 1:].contiguous()

# print(shift_logits.shape)
print(shift_labels)

log_probs = F.log_softmax(shift_logits, dim=-1)

print(attention_mask[:, 1:])
print(log_probs.shape)

log_probs_for_tokens = log_probs.gather(2, shift_labels.unsqueeze(-1)).squeeze(-1)
actual_log_probs_for_tokens = attention_mask[:, 1:] * log_probs_for_tokens

actual_nums = attention_mask[:, 1:].sum(dim=1)
actual_sums = actual_log_probs_for_tokens.sum(dim=1)
avg_logProbs = actual_sums/actual_nums
avg_logProbs.to('cpu').tolist()
# for i in range(input_ids.shape[0]):
    

# log_probs_for_tokens = log_probs.gather(2, shift_labels.unsqueeze(-1)).squeeze(-1)
# total_log_prob = log_probs_for_tokens.sum().item()
# avg_logProb = total_log_prob/len(input_ids[0])

tensor([[    40,   1093,  16558,  48510,  26769],
        [    40,   3021,    499, 128009, 128009],
        [  4071,    358,  12491,    499, 128009]], device='cuda:0')
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 0, 0],
        [1, 1, 1, 1, 0]], device='cuda:0')
torch.Size([3, 5, 128256])


[-5.16015625, -3.568359375, -5.7265625]

In [3]:
def cal_part_logprob_in_batch(_input_text: list, _tokenizer, _device):

    inputs = _tokenizer(_input_text, return_tensors="pt", padding=True, truncation=True, max_length=512).to(_device)
    attention_mask = inputs["attention_mask"]
    outputs = model(**inputs, labels=inputs["input_ids"], loss_type='ForCausalLMLoss')

    logits = outputs.logits
    input_ids = inputs["input_ids"]
    
    shift_logits = logits[: , :-1, :].contiguous()
    shift_labels = input_ids[:, 1:].contiguous()
    
    log_probs = F.log_softmax(shift_logits, dim=-1)
    
    log_probs_for_tokens = log_probs.gather(2, shift_labels.unsqueeze(-1)).squeeze(-1)
    actual_log_probs_for_tokens = attention_mask[:, 1:] * log_probs_for_tokens
    
    actual_nums = attention_mask[:, 1:].sum(dim=1)
    actual_sums = actual_log_probs_for_tokens.sum(dim=1)
    avg_logProbs = actual_sums/actual_nums
    return avg_logProbs.to('cpu').tolist()

In [18]:
cal_part_logprob('I love you', tokenizer)

(tensor([[-2.9941, -3.1719, -4.5234]], dtype=torch.float16),
 -10.6875,
 -2.671875)

##### Idea: calcuate the average logprob per token in a sentence, passage, or a multi-passage passage, it seems not difficult to calculate

In [4]:
import sys
import os
notebook_dir = os.getcwd()
project_root = os.path.abspath(os.path.join(notebook_dir, '..'))
analysis_root = os.path.abspath(os.path.join(notebook_dir, '..', 'analysis'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
if analysis_root not in sys.path:
    sys.path.insert(0, analysis_root)

from analysis.tools import coherence_cal

In [5]:
torch.cuda.empty_cache()

In [6]:
res, doc_dict, doc_length_dict = coherence_cal.get_res_and_dicts('nq_test', 'mt5')

In [7]:
import json
from tqdm import tqdm

prob_res = {}
output_path = './log_prob_temp_res/nq_test_mt5_15.json'

for qid in tqdm(res.qid.unique()):
    # qid = 'test_'+str(qid_no)
    # print(qid)
    _res_per_q = {}
    _k = 15
    _batch_size = 5
    _i = 0
    while _i < _k:
        doc_texts = res[(res.qid==qid)&(res['rank']>=_i)&(res['rank']<_i+_batch_size)].docno.apply(lambda x: doc_dict[str(x)]).tolist()
        _res_per_q = {}
        _pid = 0
        # for text in doc_texts:
        avg_logProb_list = cal_part_logprob_in_batch(doc_texts, tokenizer, device)
        torch.cuda.empty_cache()
        _res_per_q.update(dict(zip(range(_i, _i+len(doc_texts)), avg_logProb_list)))
        _i += _batch_size

    # text = ''.join(doc_texts)
    # # text = text[:-1]
    # _, _, avg_logProb = cal_part_logprob(text, tokenizer)
    # _res_per_q.update({'full': avg_logProb})
    # print(avg_logProb)
    prob_res.update({qid: _res_per_q})

    f = open(output_path, 'w')
    json.dump(prob_res, f)
    f.close()

  1%|          | 24/3610 [00:20<51:29,  1.16it/s] 


OutOfMemoryError: CUDA out of memory. Tried to allocate 510.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 422.50 MiB is free. Process 1371233 has 23.23 GiB memory in use. Of the allocated memory 22.48 GiB is allocated by PyTorch, and 570.14 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

-3.612576392389113


In [76]:
import numpy as np

np.random.seed(100)
rand_scores = np.random.rand(10)
points = np.array(range(10))
# weights = [
weights = np.array([1.0]*len(points)) # uniform
# weights = np.exp(-points) # top-heavy
# weights = np.exp(points+1-len(points)) # tail-heavy
# weights = np.exp((2*points/(len(points)-1)-1)**2) # lost-in-the-middle

print(type(weights), weights)
np.sum(weights*np.mean(rand_scores))/np.sum(weights)

<class 'numpy.ndarray'> [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


0.4425757785871915

In [72]:
np.mean(rand_scores)

0.4425757785871915

In [56]:
np.random.rand(10)

array([0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749,
       0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375])

In [57]:
np.exp((2*points/(len(points)-1)-1)**2)

array([2.71828183, 1.83113917, 1.36157481, 1.11751907, 1.0124222 ,
       1.0124222 , 1.11751907, 1.36157481, 1.83113917, 2.71828183])